### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by TitouanSans** [TitouanSans/Projet-Clavier-Virtuel#1]
N'hésiter pas à me donner votre avis sur la maquette de mon Wireframe en commentaire !
https://wireframe.cc/XgrwQv

**Comment by OliveLeb** [comment]
Tu ne mets pas de barre espace?

**Comment by Herondil** [comment]
Je n'ai pas trouvé le bouton pour le mode nuit.

**Comment by Herondil** [comment]
Il manquait aussi la touche "retour".

**Comment by TitouanSans** [comment]
Toutes les touches ont été ajouté.
